mongodb:
  uri: "mongodb://localhost:27017/" # MongoDB connection URI
  database: "grain" # Database name

server:
  port: ":8080" # Port for the server to listen on

rate_limit:
  #WS is not working as intended. It's only working for accepting Events, which is what event is supposed to do
  ws_limit: 100 # Global rate limit for WebSocket messages (50 messages per second)
  ws_burst: 200 # Global burst limit for WebSocket messages (allows a burst of 100 messages)
  #event limit doesn't seem to work either
  event_limit: 50 # Global rate limit for events (25 events per second)
  event_burst: 100 # Global burst limit for events (allows a burst of 50 events)
  req_limit: 50 # Added limit for REQ messages
  req_burst: 100 # Added burst limit for REQ messages

  category_limits: # Rate limits based on event categories
    regular:
      limit: 25 # Rate limit for regular events (50 events per second)
      burst: 50 # Burst limit for regular events (allows a burst of 100 events)
    replaceable:
      limit: 10 # Rate limit for replaceable events (10 events per second)
      burst: 20 # Burst limit for replaceable events (allows a burst of 20 events)
    parameterized_replaceable:
      limit: 5 # Rate limit for parameterized replaceable events (5 events per second)
      burst: 10 # Burst limit for parameterized replaceable events (allows a burst of 10 events)
    ephemeral:
      limit: 100 # Rate limit for ephemeral events (100 events per second)
      burst: 200 # Burst limit for ephemeral events (allows a burst of 200 events)

  kind_limits: # Specific rate limits for different kinds of events
    - kind: 0
      limit: 1 # Rate limit for events of kind 0 (1 event per second)
      burst: 5 # Burst limit for events of kind 0 (allows a burst of 5 events)
    - kind: 1
      limit: 25 # Rate limit for events of kind 1 (100 events per second)
      burst: 50 # Burst limit for events of kind 1 (allows a burst of 200 events)
    - kind: 3
      limit: 10 # Rate limit for events of kind 3 (25 events per second)
      burst: 20 # Burst limit for events of kind 3 (allows a burst of 50 events)
