package tests

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/rand"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"

	nostr "github.com/0ceanslim/grain/server/types"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcec/v2/schnorr"
	"golang.org/x/net/websocket"
)

// Default (legacy) endpoints — used by the happy-path tests in
// relay_test.go, api_test.go, websocket_test.go.
//
// We use 127.0.0.1 instead of "localhost" on purpose: docker-compose's
// port publishing on Linux binds to IPv4 0.0.0.0 only, but Go's resolver
// on some hosts (notably GitHub Actions ubuntu runners) returns ::1 for
// "localhost" first, producing intermittent "connection refused" errors
// as the test harness dials an IPv6 address docker never bound.
const (
	TestRelayURL = "ws://127.0.0.1:8182"
	TestHTTPURL  = "http://127.0.0.1:8182"
)

// Per-scenario relay endpoints. Each URL targets a dedicated docker-compose
// service backed by a config fixture in tests/docker/configs/.
const (
	DefaultRelayURL    = "ws://127.0.0.1:8182"
	RateLimitRelayURL  = "ws://127.0.0.1:8183"
	BlacklistRelayURL  = "ws://127.0.0.1:8184"
	WhitelistRelayURL  = "ws://127.0.0.1:8185"
	AuthRelayURL       = "ws://127.0.0.1:8186"
	TimeCheckRelayURL  = "ws://127.0.0.1:8187"
	EventPurgeRelayURL = "ws://127.0.0.1:8188"
	HotReloadRelayURL  = "ws://127.0.0.1:8189"

	DefaultHTTPURL    = "http://127.0.0.1:8182"
	RateLimitHTTPURL  = "http://127.0.0.1:8183"
	BlacklistHTTPURL  = "http://127.0.0.1:8184"
	WhitelistHTTPURL  = "http://127.0.0.1:8185"
	AuthHTTPURL       = "http://127.0.0.1:8186"
	TimeCheckHTTPURL  = "http://127.0.0.1:8187"
	EventPurgeHTTPURL = "http://127.0.0.1:8188"
	HotReloadHTTPURL  = "http://127.0.0.1:8189"
)

// AllRelayHTTPURLs is used by TestMain readiness checks.
var AllRelayHTTPURLs = []string{
	DefaultHTTPURL,
	RateLimitHTTPURL,
	BlacklistHTTPURL,
	WhitelistHTTPURL,
	AuthHTTPURL,
	TimeCheckHTTPURL,
	EventPurgeHTTPURL,
	HotReloadHTTPURL,
}

// WhitelistSeed MUST match tests/genconfigs/main.go.WhitelistSeed — the
// whitelist-rules.yml fixture contains the pubkey derived from this seed.
const WhitelistSeed = "grain-test-whitelist-allowed"

// TestKeypair holds a private key and its corresponding public key hex for testing.
type TestKeypair struct {
	PrivKey *btcec.PrivateKey
	PubKey  string // hex-encoded x-only public key
}

// NewTestKeypair generates a random keypair for testing.
func NewTestKeypair() *TestKeypair {
	privKey, err := btcec.NewPrivateKey()
	if err != nil {
		panic(fmt.Sprintf("failed to generate key: %v", err))
	}
	pubKey := privKey.PubKey()
	pubKeyHex := hex.EncodeToString(schnorr.SerializePubKey(pubKey))
	return &TestKeypair{PrivKey: privKey, PubKey: pubKeyHex}
}

// NewDeterministicKeypair derives a keypair from a fixed seed. The same seed
// always produces the same pubkey, so config YAML fixtures generated by
// tests/genconfigs/main.go can reference it. MUST stay in sync with
// tests/genconfigs/main.go.DerivePubKeyHex.
func NewDeterministicKeypair(seed string) *TestKeypair {
	h := sha256.Sum256([]byte(seed))
	priv, _ := btcec.PrivKeyFromBytes(h[:])
	pubHex := hex.EncodeToString(schnorr.SerializePubKey(priv.PubKey()))
	return &TestKeypair{PrivKey: priv, PubKey: pubHex}
}

// SignEventAt signs an event with a custom created_at (for drift tests).
func (kp *TestKeypair) SignEventAt(kind int, content string, tags [][]string, createdAt int64) nostr.Event {
	if tags == nil {
		tags = [][]string{}
	}
	evt := nostr.Event{
		PubKey:    kp.PubKey,
		CreatedAt: createdAt,
		Kind:      kind,
		Tags:      tags,
		Content:   content,
	}
	serialized, _ := json.Marshal([]interface{}{
		0, evt.PubKey, evt.CreatedAt, evt.Kind, evt.Tags, evt.Content,
	})
	h := sha256.Sum256(serialized)
	evt.ID = hex.EncodeToString(h[:])
	sig, err := schnorr.Sign(kp.PrivKey, h[:])
	if err != nil {
		panic(fmt.Sprintf("failed to sign event: %v", err))
	}
	evt.Sig = hex.EncodeToString(sig.Serialize())
	return evt
}

// SignEvent creates a properly signed Nostr event.
func (kp *TestKeypair) SignEvent(kind int, content string, tags [][]string) nostr.Event {
	if tags == nil {
		tags = [][]string{}
	}
	now := time.Now().Unix()

	evt := nostr.Event{
		PubKey:    kp.PubKey,
		CreatedAt: now,
		Kind:      kind,
		Tags:      tags,
		Content:   content,
	}

	// Serialize per NIP-01: [0, pubkey, created_at, kind, tags, content]
	serialized, _ := json.Marshal([]interface{}{
		0, evt.PubKey, evt.CreatedAt, evt.Kind, evt.Tags, evt.Content,
	})

	// Compute ID
	hash := sha256.Sum256(serialized)
	evt.ID = hex.EncodeToString(hash[:])

	// Sign with schnorr
	sig, err := schnorr.Sign(kp.PrivKey, hash[:])
	if err != nil {
		panic(fmt.Sprintf("failed to sign event: %v", err))
	}
	evt.Sig = hex.EncodeToString(sig.Serialize())

	return evt
}

// TestClient wraps a WebSocket connection for testing
type TestClient struct {
	conn *websocket.Conn
	t    *testing.T
}

// NewTestClient creates a new WebSocket connection to the default test relay.
func NewTestClient(t *testing.T) *TestClient {
	return NewTestClientAt(t, DefaultRelayURL)
}

// NewTestClientAt creates a new WebSocket connection to the given relay URL.
func NewTestClientAt(t *testing.T, url string) *TestClient {
	origin := "http://localhost/"
	conn, err := websocket.Dial(url, "", origin)
	if err != nil {
		t.Fatalf("Failed to connect to relay %s: %v", url, err)
	}
	return &TestClient{conn: conn, t: t}
}

// SendMessage sends a message to the relay
func (c *TestClient) SendMessage(msg interface{}) {
	msgBytes, err := json.Marshal(msg)
	if err != nil {
		c.t.Fatalf("Failed to marshal message: %v", err)
	}

	_, err = c.conn.Write(msgBytes)
	if err != nil {
		c.t.Fatalf("Failed to send message: %v", err)
	}
}

// SendEvent publishes an EVENT message to the relay
func (c *TestClient) SendEvent(evt nostr.Event) {
	c.SendMessage([]interface{}{"EVENT", evt})
}

// Subscribe sends a REQ with the given subscription ID and filters
func (c *TestClient) Subscribe(subID string, filters ...map[string]interface{}) {
	msg := make([]interface{}, 2+len(filters))
	msg[0] = "REQ"
	msg[1] = subID
	for i, f := range filters {
		msg[2+i] = f
	}
	c.SendMessage(msg)
}

// ReadMessage reads a message from the relay with timeout
func (c *TestClient) ReadMessage(timeout time.Duration) []interface{} {
	c.conn.SetReadDeadline(time.Now().Add(timeout))

	msgBytes := make([]byte, 65536)
	n, err := c.conn.Read(msgBytes)
	if err != nil {
		c.t.Fatalf("Failed to read message: %v", err)
	}

	var msg []interface{}
	err = json.Unmarshal(msgBytes[:n], &msg)
	if err != nil {
		c.t.Fatalf("Failed to unmarshal message: %v", err)
	}

	return msg
}

// ReadMessageRaw reads a raw JSON message from the relay
func (c *TestClient) ReadMessageRaw(timeout time.Duration) json.RawMessage {
	c.conn.SetReadDeadline(time.Now().Add(timeout))

	msgBytes := make([]byte, 65536)
	n, err := c.conn.Read(msgBytes)
	if err != nil {
		c.t.Fatalf("Failed to read message: %v", err)
	}

	return json.RawMessage(msgBytes[:n])
}

// ExpectOK reads messages until it gets an OK for the given event ID.
// Returns (accepted bool, message string).
func (c *TestClient) ExpectOK(eventID string, timeout time.Duration) (bool, string) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		msg := c.ReadMessage(time.Until(deadline))
		if len(msg) >= 4 && msg[0] == "OK" {
			if id, ok := msg[1].(string); ok && id == eventID {
				accepted, _ := msg[2].(bool)
				reason, _ := msg[3].(string)
				return accepted, reason
			}
		}
	}
	c.t.Fatalf("Timed out waiting for OK response for event %s", eventID)
	return false, ""
}

// ExpectEOSE reads messages until it gets an EOSE for the given subscription ID.
// Returns any EVENT messages received before the EOSE.
func (c *TestClient) ExpectEOSE(subID string, timeout time.Duration) []map[string]interface{} {
	var events []map[string]interface{}
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		msg := c.ReadMessage(time.Until(deadline))
		if len(msg) >= 2 {
			if msg[0] == "EOSE" {
				if sid, ok := msg[1].(string); ok && sid == subID {
					return events
				}
			}
			if msg[0] == "EVENT" && len(msg) >= 3 {
				if sid, ok := msg[1].(string); ok && sid == subID {
					if evtMap, ok := msg[2].(map[string]interface{}); ok {
						events = append(events, evtMap)
					}
				}
			}
		}
	}
	c.t.Fatalf("Timed out waiting for EOSE for subscription %s", subID)
	return nil
}

// Close closes the WebSocket connection
func (c *TestClient) Close() {
	c.conn.Close()
}

// WaitForRelayReady waits for the default relay to be ready.
func WaitForRelayReady(t *testing.T, maxAttempts int) {
	WaitForRelayReadyAt(t, DefaultHTTPURL, maxAttempts)
}

// readyClient has a short per-request timeout so a container that accepts
// TCP but never completes an HTTP response cannot hang the test process.
var readyClient = &http.Client{Timeout: 2 * time.Second}

// WaitForRelayReadyAt waits for a specific relay endpoint to be ready.
// Returns an error (rather than t.Fatalf) so callers in TestMain — where
// no real *testing.T exists — can handle the failure themselves.
func WaitForRelayReadyAt(t *testing.T, httpURL string, maxAttempts int) {
	if err := waitForRelayReady(httpURL, maxAttempts); err != nil {
		t.Fatal(err)
	}
}

func waitForRelayReady(httpURL string, maxAttempts int) error {
	var lastErr error
	for i := 0; i < maxAttempts; i++ {
		resp, err := readyClient.Get(httpURL)
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode == 200 {
				return nil
			}
			lastErr = fmt.Errorf("status %d", resp.StatusCode)
		} else {
			lastErr = err
		}
		time.Sleep(1 * time.Second)
	}
	return fmt.Errorf("relay %s not ready after %d attempts: %v", httpURL, maxAttempts, lastErr)
}

// WaitForAllRelaysReady pings every per-scenario relay endpoint in
// parallel so one slow-starting container can't block the others.
// Progress is logged to stderr for CI visibility.
func WaitForAllRelaysReady(maxAttempts int) error {
	type result struct {
		url string
		err error
	}
	results := make(chan result, len(AllRelayHTTPURLs))
	for _, url := range AllRelayHTTPURLs {
		url := url
		go func() {
			fmt.Fprintf(os.Stderr, "waiting for %s...\n", url)
			err := waitForRelayReady(url, maxAttempts)
			if err != nil {
				fmt.Fprintf(os.Stderr, "  FAIL %s: %v\n", url, err)
			} else {
				fmt.Fprintf(os.Stderr, "  ok   %s\n", url)
			}
			results <- result{url, err}
		}()
	}
	var firstErr error
	for range AllRelayHTTPURLs {
		r := <-results
		if r.err != nil && firstErr == nil {
			firstErr = r.err
		}
	}
	return firstErr
}

// ExpectNotice reads messages until a NOTICE is received, then returns its
// message text. Fails if one doesn't arrive before timeout.
func (c *TestClient) ExpectNotice(timeout time.Duration) string {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		msg := c.ReadMessage(time.Until(deadline))
		if len(msg) >= 2 && msg[0] == "NOTICE" {
			if s, ok := msg[1].(string); ok {
				return s
			}
		}
	}
	c.t.Fatalf("Timed out waiting for NOTICE")
	return ""
}

// ExpectClosed reads messages until a CLOSED for subID is received.
func (c *TestClient) ExpectClosed(subID string, timeout time.Duration) string {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		msg := c.ReadMessage(time.Until(deadline))
		if len(msg) >= 3 && msg[0] == "CLOSED" {
			if sid, ok := msg[1].(string); ok && sid == subID {
				reason, _ := msg[2].(string)
				return reason
			}
		}
	}
	c.t.Fatalf("Timed out waiting for CLOSED for %s", subID)
	return ""
}

// ExpectAuthChallenge reads messages until an AUTH challenge frame arrives and
// returns the challenge string.
func (c *TestClient) ExpectAuthChallenge(timeout time.Duration) string {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		msg := c.ReadMessage(time.Until(deadline))
		if len(msg) >= 2 && msg[0] == "AUTH" {
			if s, ok := msg[1].(string); ok {
				return s
			}
		}
	}
	c.t.Fatalf("Timed out waiting for AUTH challenge")
	return ""
}

// PerformAuth executes a NIP-42 challenge/response exchange: reads the AUTH
// challenge, signs a kind-22242 event with the required relay + challenge
// tags, sends it, and waits for OK. Returns the OK message text.
func (c *TestClient) PerformAuth(kp *TestKeypair, relayURL string, timeout time.Duration) (bool, string) {
	challenge := c.ExpectAuthChallenge(timeout)
	tags := [][]string{
		{"relay", relayURL},
		{"challenge", challenge},
	}
	evt := kp.SignEvent(22242, "", tags)
	c.SendMessage([]interface{}{"AUTH", evt})
	return c.ExpectOK(evt.ID, timeout)
}

// ContainsAny reports whether s contains any of the given substrings. Handy
// for matching reject messages against alternatives.
func ContainsAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, sub) {
			return true
		}
	}
	return false
}

// RandomSubID generates a random subscription ID for tests.
func RandomSubID() string {
	return fmt.Sprintf("test-%d", rand.Intn(1000000))
}
